import test from 'node:test';
import assert from 'node:assert/strict';
import { createCandidateController } from './legacy/src/candidate-ui.js';
function harness() {
 const element=()=>({value:'',textContent:'',children:[],hidden:true,disabled:false,attributes:{},listeners:{},files:[],append(...items){this.children.push(...items);},replaceChildren(...items){this.children=items;},setAttribute(key,value){this.attributes[key]=value;},addEventListener(name,callback){this.listeners[name]=callback;},focus(){}});
 const elements={},get=id=>elements[id]||=element(),timers=new Map(),requests=[];let id=0;
 const state={confirmedJobProfile:{confirmed:true},confirmedRequirementsProfile:{confirmed:true,technical:{requiredSkills:[{value:'Appium'}]}}};
 const controller=createCandidateController(state,{querySelector:selector=>get(selector.slice(1)),createElement:element},{schedule:cb=>{timers.set(++id,cb);return id;},cancel:id=>timers.delete(id),fetchResume:(target,options)=>new Promise((resolve,reject)=>requests.push({target,options,resolve,reject}))});
 const text=node=>[node.textContent,...node.children.map(text)].join(' ');
 const submit=id=>get(id).listeners.submit({preventDefault(){}});
 const file=(name='resume.pdf')=>{get('candidate-upload').files=[{name,size:200,type:'application/pdf'}];};
 const response=async(index,text='Jane Doe\nQA Engineer\nSkills\nSelenium')=>{requests[index].resolve({ok:true,json:async()=>({text,file:{name:'resume.pdf'},pageCount:1,warnings:[],extractionStatus:'extracted'})});await Promise.resolve();await Promise.resolve();await Promise.resolve();};
 controller.onRequirementsConfirmed();get('candidate-add-button').listeners.click();return{get,state,controller,text,submit,file,response,requests,timers};
}
test('Day 5 gates upload on both confirmed job objects',()=>{const h=harness();h.state.confirmedRequirementsProfile=null;h.controller.onRequirementsConfirmed();assert.equal(h.get('candidate-section').hidden,true);h.file();h.submit('candidate-upload-form');assert.equal(h.requests.length,0);});
test('resume read/review/confirmation preserves independent job facts and displays evidence',async()=>{const h=harness(),job=JSON.stringify(h.state.confirmedRequirementsProfile);h.file();const pending=h.submit('candidate-upload-form');assert.equal(h.state.resumeStatus,'extracting');assert.equal(h.get('candidate-message').textContent,'Reading your resume...');await h.response(0);await pending;assert.equal(h.state.candidateStatus,'reviewing');assert.match(h.text(h.get('candidate-results')),/Evidence: skills/);h.get('candidate-confirm-button').listeners.click();assert.equal(h.state.confirmedCandidateProfile.confirmed,true);assert.equal(h.state.confirmedCandidateProfile.skills.items.some(item=>item.value==='Appium'),false);assert.equal(JSON.stringify(h.state.confirmedRequirementsProfile),job);});
test('replacement cancels stale read, removes old candidate and retains job requirements',async()=>{const h=harness();h.file();const first=h.submit('candidate-upload-form');h.file('new.pdf');const second=h.submit('candidate-upload-form');assert.equal(h.requests[0].options.signal.aborted,true);await h.response(1,'New Person\nSkills\nPlaywright');await second;await h.response(0);await first;assert.equal(h.state.draftCandidateProfile.identity.name.value,'New Person');assert.equal(h.state.draftCandidateProfile.skills.items.some(item=>item.value==='Selenium WebDriver'),false);assert.equal(h.state.confirmedRequirementsProfile.confirmed,true);});
test('candidate clear empties all personal inputs, cancels read and keeps the job',async()=>{const h=harness();h.file();const pending=h.submit('candidate-upload-form');h.get('candidate-context-noticePeriod').value='Immediate';h.get('candidate-previous-email').value='Old email';h.controller.clear();assert.equal(h.get('candidate-context-noticePeriod').value,'');assert.equal(h.get('candidate-previous-email').value,'');assert.equal(h.state.confirmedRequirementsProfile.confirmed,true);await h.response(0);await pending;assert.equal(h.state.draftCandidateProfile,null);assert.equal(h.state.extractedResumeText,'');});
test('additional context invalidates confirmation, previous email remains only writing context',async()=>{const h=harness();h.file();const pending=h.submit('candidate-upload-form');await h.response(0);await pending;h.get('candidate-confirm-button').listeners.click();h.get('candidate-context-noticePeriod').value='Immediate';h.get('candidate-context-noticePeriod').listeners.input();assert.equal(h.state.confirmedCandidateProfile,null);h.get('candidate-previous-email').value='10 years Appium';h.get('candidate-previous-email').listeners.input();h.get('candidate-confirm-button').listeners.click();assert.equal(h.state.confirmedCandidateProfile.applicationContext.noticePeriod.source,'user_provided');assert.equal(h.state.confirmedCandidateProfile.writingContext.previousApplicationEmail,'10 years Appium');assert.equal(h.state.confirmedCandidateProfile.skills.items.length,1);});
test('editing and cancel require reconfirmation; saving corrections leaves original text intact',async()=>{const h=harness();h.file();const pending=h.submit('candidate-upload-form');await h.response(0);await pending;h.get('candidate-confirm-button').listeners.click();h.get('candidate-edit-button').listeners.click();assert.equal(h.state.confirmedCandidateProfile,null);h.get('candidate-edit-name').value='Correct Name';h.submit('candidate-edit-form');assert.equal(h.state.draftCandidateProfile.identity.name.source,'user_provided');assert.match(h.state.extractedResumeText,/Jane Doe/);h.get('candidate-confirm-button').listeners.click();assert.equal(h.state.confirmedCandidateProfile.identity.name.value,'Correct Name');});
test('upstream job invalidation cancels resume processing and prevents stale candidate confirmation',async()=>{const h=harness();h.file();const pending=h.submit('candidate-upload-form');h.controller.invalidateJob();h.state.confirmedRequirementsProfile=null;await h.response(0);await pending;assert.equal(h.state.draftCandidateProfile,null);assert.equal(h.state.confirmedCandidateProfile,null);assert.equal(h.get('candidate-section').hidden,true);});
test('manual entry has user provenance and can confirm without a readable document',()=>{const h=harness();h.get('candidate-manual-text').value='Jane Doe\nSkills\nSelenium';h.submit('candidate-manual-form');h.get('candidate-confirm-button').listeners.click();assert.equal(h.state.confirmedCandidateProfile.identity.name.source,'user_provided');assert.equal(h.state.confirmedCandidateProfile.source.originalResumeText,'');assert.equal(h.state.resumeFile,null);});
test('read failure restores upload and leaves job requirements intact',async()=>{const h=harness();h.file();const pending=h.submit('candidate-upload-form');h.requests[0].resolve({ok:false,json:async()=>({error:{message:'Corrupted document. Try another file.'}})});await pending;assert.equal(h.state.resumeStatus,'failed');assert.equal(h.get('candidate-upload-button').disabled,false);assert.match(h.get('candidate-message').textContent,/Corrupted/);assert.equal(h.state.confirmedRequirementsProfile.confirmed,true);});
test('client validates absent, empty, oversized and unsupported files without uploading',()=>{const h=harness();h.submit('candidate-upload-form');assert.match(h.get('candidate-message').textContent,/select/);for(const file of [{name:'file.pdf',type:'application/pdf',size:0},{name:'file.pdf',type:'application/pdf',size:5*1024*1024},{name:'file.exe',type:'application/pdf',size:100},{name:'file.pdf',type:'text/html',size:100}]){h.get('candidate-upload').files=[file];h.submit('candidate-upload-form');}assert.equal(h.requests.length,0);});
