import test from 'node:test';
import assert from 'node:assert/strict';
import {createRelevanceController} from './legacy/src/relevance-ui.js';
import {matchProfiles} from '../src/relevance-engine.js';
import {jobProfile,candidateProfile} from './relevance-fixtures.js';
function harness(match) {
 const element=()=>({value:'',textContent:'',hidden:true,disabled:true,children:[],listeners:{},attributes:{},append(...nodes){this.children.push(...nodes);},replaceChildren(...nodes){this.children=nodes;},setAttribute(key,value){this.attributes[key]=value;},addEventListener(key,fn){this.listeners[key]=fn;}});
 const elements={},get=id=>elements[id]||=element(),timers=new Map();let id=0;
 const state={confirmedRequirementsProfile:jobProfile('Required Skills: Selenium, Appium\nPreferred Skills: Cypress'),confirmedCandidateProfile:candidateProfile()};
 const controller=createRelevanceController(state,{querySelector:selector=>get(selector.slice(1)),createElement:element},{match,schedule:fn=>{timers.set(++id,fn);return id;},cancel:id=>timers.delete(id)});
 const run=()=>{for(const[id,fn]of [...timers]){timers.delete(id);fn();}};
 const text=node=>[node.textContent,...node.children.map(text)].join(' ');
 const nodes=(node,fn)=>[...(fn(node)?[node]:[]),...node.children.flatMap(child=>nodes(child,fn))];
 controller.onCandidateConfirmed();return{state,controller,get,run,text,nodes,timers};
}
test('both confirmed profiles gate matching and repeated clicks do not schedule duplicate runs',()=>{const h=harness();h.state.confirmedCandidateProfile=null;h.controller.onCandidateConfirmed();h.get('match-button').listeners.click();assert.equal(h.timers.size,0);assert.equal(h.get('match-section').hidden,true);});
test('match lifecycle renders requirements, evidence, gaps and a confirmed grounding handoff',()=>{const h=harness(),before=JSON.stringify([h.state.confirmedRequirementsProfile,h.state.confirmedCandidateProfile]);h.get('match-button').listeners.click();assert.equal(h.state.matchStatus,'matching');assert.equal(h.get('match-message').textContent,'Comparing your profile with this job...');h.get('match-button').listeners.click();assert.equal(h.timers.size,1);h.run();assert.equal(h.state.matchStatus,'reviewing');const rendered=h.text(h.get('match-results'));assert.match(rendered,/Required Skills/);assert.match(rendered,/Preferred Skills/);assert.match(rendered,/Candidate evidence/);assert.match(rendered,/No Verified Match/);assert.match(rendered,/Do Not Claim/);assert.match(rendered,/not an interview or hiring probability/);h.get('match-confirm-button').listeners.click();assert.equal(h.state.matchStatus,'confirmed');assert.equal(h.state.confirmedRelevanceProfile.confirmed,true);assert.ok(h.state.confirmedRelevanceProfile.emailGroundingContext.selectedHighlights.length);assert.equal(JSON.stringify([h.state.confirmedRequirementsProfile,h.state.confirmedCandidateProfile]),before);});
test('highlight removal invalidates confirmation and add selects only verified facts',()=>{const h=harness();h.get('match-button').listeners.click();h.run();h.get('match-confirm-button').listeners.click();const checkbox=h.nodes(h.get('match-highlight-options'),node=>node.type==='checkbox')[0],before=h.state.draftRelevanceProfile.selectedHighlightIds.length;checkbox.listeners.change();assert.equal(h.state.confirmedRelevanceProfile,null);assert.equal(h.state.draftRelevanceProfile.selectedHighlightIds.length,before-1);const extra=h.state.draftRelevanceProfile.highlightOptions.find(item=>!h.state.draftRelevanceProfile.selectedHighlightIds.includes(item.id));h.get('match-add-select').value=extra.id;h.get('match-add-button').listeners.click();assert.ok(h.state.draftRelevanceProfile.selectedHighlightIds.includes(extra.id));h.get('match-add-select').value='unsupported claim';h.get('match-add-button').listeners.click();assert.equal(h.state.draftRelevanceProfile.selectedHighlightIds.includes('unsupported claim'),false);assert.match(h.get('match-message').textContent,/verified candidate/);});
test('profile invalidation clears results, selected highlight controls and scheduled matching',()=>{const h=harness();h.get('match-button').listeners.click();h.controller.invalidate();h.run();assert.equal(h.state.draftRelevanceProfile,null);assert.equal(h.state.confirmedRelevanceProfile,null);assert.equal(h.get('match-section').hidden,true);assert.equal(h.get('match-results').children.length,0);assert.equal(h.get('match-highlight-options').children.length,0);assert.equal(h.get('match-section').attributes['aria-busy'],'false');});
test('failed matching retains original confirmed profiles and supports retry',()=>{let attempts=0;const h=harness((j,c)=>{if(!attempts++)throw new Error('failure');return matchProfiles(j,c);});const j=h.state.confirmedRequirementsProfile,c=h.state.confirmedCandidateProfile;h.get('match-button').listeners.click();h.run();assert.equal(h.state.matchStatus,'match_failed');assert.equal(h.get('match-retry-button').hidden,false);assert.equal(h.state.confirmedRequirementsProfile,j);assert.equal(h.state.confirmedCandidateProfile,c);h.get('match-retry-button').listeners.click();h.run();assert.equal(h.state.matchStatus,'reviewing');});
test('stale profiles cannot be confirmed and must be recalculated',()=>{const h=harness();h.get('match-button').listeners.click();h.run();h.state.confirmedCandidateProfile.identity.name.value='Changed';h.get('match-confirm-button').listeners.click();assert.equal(h.state.confirmedRelevanceProfile,null);assert.match(h.get('match-message').textContent,/Recalculate/);});
test('untrusted candidate text is rendered as text with no HTML evaluation',()=>{const h=harness();h.state.confirmedCandidateProfile.applicationContext.availability={value:'<img src=x onerror=alert(1)>',source:'user_provided',userConfirmed:true,evidence:[]};h.get('match-button').listeners.click();h.run();h.get('match-add-select').value='candidate:applicationContext.availability';h.get('match-add-button').listeners.click();assert.match(h.text(h.get('match-highlight-options')),/<img src=x onerror=alert\(1\)>/);});
test('confirm then recalculate invalidates previous handoff before the new run finishes',()=>{const h=harness();h.get('match-button').listeners.click();h.run();h.get('match-confirm-button').listeners.click();h.get('match-button').listeners.click();assert.equal(h.state.confirmedRelevanceProfile,null);assert.equal(h.state.matchStatus,'matching');h.run();assert.equal(h.state.matchStatus,'reviewing');});
