import test from 'node:test';
import assert from 'node:assert/strict';
import { readResume,validateResume,MAX_RESUME_BYTES } from '../src/server/resume-reader.js';
import { createAppServer } from './legacy/server.js';
export function pdfFixture(pages) {
 const objects=['<< /Type /Catalog /Pages 2 0 R >>',`<< /Type /Pages /Kids [${pages.map((_,i)=>`${3+i*2} 0 R`).join(' ')}] /Count ${pages.length} >>`];
 const font=3+pages.length*2;
 for(let i=0;i<pages.length;i++){const stream=pages[i]?`BT /F1 12 Tf 50 750 Td (${pages[i].replace(/[()\\]/g,'\\$&')}) Tj ET`:'';objects.push(`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 ${font} 0 R >> >> /Contents ${4+i*2} 0 R >>`,`<< /Length ${Buffer.byteLength(stream)} >>\nstream\n${stream}\nendstream`);}
 objects.push('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>');let text='%PDF-1.4\n',offsets=[0];objects.forEach((obj,i)=>{offsets.push(Buffer.byteLength(text));text+=`${i+1} 0 obj\n${obj}\nendobj\n`;});const xref=Buffer.byteLength(text);text+=`xref\n0 ${objects.length+1}\n0000000000 65535 f \n${offsets.slice(1).map(offset=>`${String(offset).padStart(10,'0')} 00000 n \n`).join('')}trailer\n<< /Size ${objects.length+1} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;return Buffer.from(text);
}
function zipFixture(entries) {
 const locals=[],central=[];let offset=0;
 for(const [name,text]of entries){const data=Buffer.from(text),filename=Buffer.from(name),header=Buffer.alloc(30);header.writeUInt32LE(0x04034b50);header.writeUInt16LE(20,4);header.writeUInt32LE(data.length,18);header.writeUInt32LE(data.length,22);header.writeUInt16LE(filename.length,26);locals.push(header,filename,data);const c=Buffer.alloc(46);c.writeUInt32LE(0x02014b50);c.writeUInt16LE(20,4);c.writeUInt16LE(20,6);c.writeUInt32LE(data.length,20);c.writeUInt32LE(data.length,24);c.writeUInt16LE(filename.length,28);c.writeUInt32LE(offset,42);central.push(c,filename);offset+=30+filename.length+data.length;}
 const directory=Buffer.concat(central),end=Buffer.alloc(22);end.writeUInt32LE(0x06054b50);end.writeUInt16LE(entries.length,8);end.writeUInt16LE(entries.length,10);end.writeUInt32LE(directory.length,12);end.writeUInt32LE(offset,16);return Buffer.concat([...locals,directory,end]);
}
export const docxFixture=()=>zipFixture([['[Content_Types].xml','<Types/>'],['word/document.xml','<w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:body><w:p><w:r><w:t>Jane Doe</w:t></w:r></w:p><w:p><w:r><w:t>QA Engineer skilled in Selenium and Java</w:t></w:r></w:p><w:tbl><w:tr><w:tc><w:p><w:r><w:t>Work experience in software testing</w:t></w:r></w:p></w:tc></w:tr></w:tbl></w:body></w:document>'],['word/header1.xml','<w:hdr xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:p><w:r><w:t>jane@example.com</w:t></w:r></w:p></w:hdr>']]);
test('PDF reads all pages and DOCX reads paragraphs, tables and headers',async()=>{const pdf=await readResume(pdfFixture(['Jane Doe QA Engineer with Selenium experience','Education and project experience with Playwright']),{filename:'resume.pdf'});assert.equal(pdf.pageCount,2);assert.match(pdf.text,/Selenium/);assert.match(pdf.text,/Playwright/);const doc=await readResume(docxFixture(),{filename:'resume.docx'});assert.match(doc.text,/Jane Doe\nQA Engineer/);assert.match(doc.text,/Work experience/);assert.match(doc.text,/jane@example.com/);});
test('empty/image-only PDFs fail and partial PDFs preserve readable pages',async()=>{await assert.rejects(readResume(pdfFixture(['']),{filename:'empty.pdf'}),/couldn't reliably read/);const p=await readResume(pdfFixture(['Jane Doe QA Engineer with meaningful text','']),{filename:'partial.pdf'});assert.equal(p.extractionStatus,'partial');assert.equal(p.warnings.length,1);assert.match(p.text,/Jane Doe/);});
test('unsupported, spoofed, zero-length, oversized and corrupt uploads fail gracefully',async()=>{assert.throws(()=>validateResume(Buffer.from('text'),'file.exe'),/PDF or DOCX/);assert.throws(()=>validateResume(Buffer.from('text'),'file.pdf'),/does not match/);assert.throws(()=>validateResume(Buffer.alloc(0),'file.pdf'),/non-empty/);assert.throws(()=>validateResume(Buffer.alloc(MAX_RESUME_BYTES),'file.pdf'),/5 MB/);assert.throws(()=>validateResume(pdfFixture(['text']),'file.pdf','text/plain'),/PDF or DOCX/);await assert.rejects(readResume(Buffer.from('%PDF-broken'),{filename:'file.pdf'}));await assert.rejects(readResume(Buffer.from([80,75,3,4,0]),{filename:'file.docx'}));});
test('ZIP impostors, macros and excessive expansion are rejected before processing',async()=>{await assert.rejects(readResume(zipFixture([['hello.txt','hello world']]),{filename:'file.docx'}));const macro=zipFixture([['[Content_Types].xml','<Types/>'],['word/document.xml','<document/>'],['word/vbaProject.bin','not executed']]);await assert.rejects(readResume(macro,{filename:'file.docx'}));const bomb=docxFixture();const end=bomb.length-22,central=bomb.readUInt32LE(end+16);bomb.writeUInt32LE(30*1024*1024,central+24);await assert.rejects(readResume(bomb,{filename:'file.docx'}));});
test('resume processing timeout and cancellation terminate the reader',async()=>{await assert.rejects(readResume(pdfFixture(['Jane Doe meaningful resume text']),{filename:'file.pdf',timeout:1}),/couldn't reliably read/);const controller=new AbortController();controller.abort();await assert.rejects(readResume(pdfFixture(['text']),{filename:'file.pdf',signal:controller.signal}),/cancelled/);});
test('password-protected PDF gives a specific recoverable error',async()=>{const source=pdfFixture(['Jane Doe meaningful resume text']).toString();const encrypted=Buffer.from(source.replace('/Root 1 0 R >>',`/Root 1 0 R /Encrypt << /Filter /Standard /V 1 /R 2 /Length 40 /O <${'01'.repeat(32)}> /U <${'02'.repeat(32)}> /P -4 >> /ID [<${'00'.repeat(16)}> <${'00'.repeat(16)}>] >>`));await assert.rejects(readResume(encrypted,{filename:'locked.pdf'}),error=>error.code==='password_protected'&&/password-protected/.test(error.message));});
test('HTTP upload accepts raw document, serves modules, prevents cross-origin upload and returns readable errors',async()=>{const server=createAppServer();await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const base=`http://127.0.0.1:${server.address().port}`;try{const res=await fetch(`${base}/api/read-resume`,{method:'POST',headers:{'Content-Type':'application/pdf','X-Resume-Name':'resume.pdf'},body:pdfFixture(['Jane Doe with meaningful Selenium experience'])});assert.equal(res.status,200);assert.match((await res.json()).text,/Selenium/);const cross=await fetch(`${base}/api/read-resume`,{method:'POST',headers:{Origin:'https://example.com'},body:'x'});assert.equal(cross.status,403);const invalid=await fetch(`${base}/api/read-resume`,{method:'POST',headers:{'X-Resume-Name':'file.exe'},body:'x'});assert.equal(invalid.status,415);for(const path of ['/src/candidate-ui.js','/src/candidate-profile.js'])assert.equal((await fetch(base+path)).status,200);}finally{server.closeAllConnections();await new Promise(resolve=>server.close(resolve));}});
